### ISSUE TITLE
Add filters support for subscription

### ISSUE THREAD

**Issue by SaugataDutta** [terraform-google-modules/terraform-google-pubsub#31]
Can we have support for this..This is a beta feature but still very useful. 
https://cloud.google.com/pubsub/docs/filtering

**Comment by morgante** [comment]
It's not supported on the provider yet, please file an issue there: https://github.com/terraform-providers/terraform-provider-google/issues

**Comment by nyc3-szheng** [comment]
looks like the filter feature has been added to the provide as of august 11th 

https://github.com/hashicorp/terraform-provider-google/blob/4e52f41d5051978fb3de54e3f48ebc8c08d17347/.changelog/3759.txt
