### ISSUE TITLE
call multiple modules, or support multiple topics/subscriptions

### ISSUE THREAD

**Issue by evanrich** [terraform-google-modules/terraform-google-pubsub#61]
This module seems to only support one invocation, as calling it twice throws an error about duplicate modules.  If you needed to create multiple topics, each with a set of subscriptions, is that not supported?   sorry I'm kinda new to TF.

Using version 1.8

**Comment by morgante** [comment]
You just need to name each instance differently.

Ex.

```hcl

module "pubsub-1" {
  source  = "terraform-google-modules/pubsub/google"
  version = "~> 1.8"

  topic      = "tf-topic"
}

module "pubsub-2" {
  source  = "terraform-google-modules/pubsub/google"
  version = "~> 1.8"

  topic      = "tf-topic-2"
}
```
