### ISSUE TITLE
Problem with subscription labels

### ISSUE THREAD

**Issue by emilianooddo** [terraform-google-modules/terraform-google-pubsub#62]
Hi,
I have a problem with the subscription labels. If I pass a map(string) as required by the variable, I receive the following error for both push and pull subscription:

**The given value is not suitable for child module variable "pull_subscriptions"
defined at modules\pubsub\variables.tf:45,1-30: element 0: element "labels":
string required.**

Instead, if I pass a string (following the error), the TF plan dosn't give any error, but the label is not applied.

I receive a similar error, if I try to pass different labels for each subscription (push/pull) of the list.

does anyone have the same problem as me or am I wrong something?

thanks in advance

**Comment by corqueeuvia** [comment]
@emilianooddo hey, remember how you fixed this? facing the same issue here 😟

**Comment by robinfelix25** [comment]
@emilianooddo @corqueeuvia Facing the same issue, got any luck ? 🙂
