### ISSUE TITLE
Allow creating subscriptions for existing topics

### ISSUE THREAD

**Issue by nikahkeller** [terraform-google-modules/terraform-google-pubsub#71]
Hello,

Currently, you are not able to create subscriptions if you set create_topic to false. This doesn't let you create subs separately from topics. This is useful when your topic is used by one application and is in a google project that is different from a google project that needs a sub for a different application. This is where is constraint is set for pull subs:

https://github.com/terraform-google-modules/terraform-google-pubsub/blob/master/main.tf#L178

Thanks,

**Comment by onimsha** [comment]
@nikahkeller not sure if it's still relevant to you but i made a PR to address this issue.
