### ISSUE TITLE
Unsupported attribute error on "subscription_paths"

### ISSUE THREAD

**Issue by hoshiin** [terraform-google-modules/terraform-google-pubsub#84]
### TL;DR

When I run `terraform plan` without changing anything in the source code, I get an error.

### Expected behavior

`terraform plan` should terminates successfully. The pubsub resource has already been created by terraform, so nothing should be changed.

### Observed behavior

```
Error: Unsupported attribute
on .terraform/modules/pubsub.pubsub/outputs.tf line 49, in output "subscription_paths":
 google_pubsub_subscription.pull_subscriptions.*.path,
This object does not have an attribute named "path".
```

### Terraform Configuration

```hcl
module "pubsub" {
  source  = "terraform-google-modules/pubsub/google"
  version = "~> 1.3"
  topic              = "app"
  project_id         = var.project_id
  pull_subscriptions = [
    {
      name                       = "app"
      ack_deadline_seconds       = "60"
      message_retention_duration = "604800s" 
      retain_acked_messages      = "false"
      enable_message_ordering    = "false"
      dead_letter_policy         = "false"
    },
  ]
}
```

### Terraform Version

```sh
docker.io/hashicorp/terraform:1.0.7
hashicorp/terraform:1.0.7
on linux_amd64
hashicorp/google-beta v4.5.0
hashicorp/google v4.5.0
hashicorp/random v3.1.0
```

**Comment by SoftBakedVlad** [comment]
@hoshiin I think you should upgrade module version to `3.1.0`. See: https://github.com/terraform-google-modules/terraform-google-pubsub/pull/78

**Comment by hoshiin** [comment]
@SoftBakedVlad When I run `terraform plan` with the module `3.1.0`, the error is avoided. However, in the execution plan, the resources are being destroyed and created.
Is there any way to work around this error without destroying the resources?
